### ISSUE TITLE
Can TEMPLATE_DIR be a URL?

### ISSUE THREAD

**Issue by buckmaxwell** [vintasoftware/django-templated-email#117]
I would like to store templates on cloudfront or an S3 bucket. Is this possible?

**Comment by chocoelho** [comment]
We take advantage of the behavior of `TEMPLATE_DIR` in Django, so IIRC it won't work out-of-the-box. To achieve something like this, it'd require some tweaking around Django's template loader system, which probably changed a bit since 2.0. So I'll be closing this as this is something not related to `django-templated-email` itself, but rather a change on how Django manages its templates. Feel free to reopen this if you feel like it needs more discussing.
